-- ============================================================
-- Retail Executive Analytics Platform
-- Dimension tables (star schema)
-- ============================================================

CREATE TABLE dim_date (
    date_id         INT PRIMARY KEY,              -- YYYYMMDD
    full_date       DATE NOT NULL UNIQUE,
    year            SMALLINT NOT NULL,
    quarter         SMALLINT NOT NULL,
    month           SMALLINT NOT NULL,
    month_name      VARCHAR(10) NOT NULL,
    week_of_year    SMALLINT NOT NULL,
    day_of_month    SMALLINT NOT NULL,
    day_of_week     SMALLINT NOT NULL,            -- ISO: 1=Monday .. 7=Sunday
    day_name        VARCHAR(10) NOT NULL,
    is_weekend      BOOLEAN NOT NULL,
    is_holiday      BOOLEAN NOT NULL DEFAULT FALSE,
    holiday_name    VARCHAR(50)
);

CREATE TABLE dim_store (
    store_id        SERIAL PRIMARY KEY,
    store_code      VARCHAR(10) NOT NULL UNIQUE,
    store_name      VARCHAR(100) NOT NULL,
    store_type      VARCHAR(20) NOT NULL,         -- Flagship, Standard, Outlet
    region          VARCHAR(30) NOT NULL,         -- Northeast, Midwest, South, West
    state           VARCHAR(2) NOT NULL,
    city            VARCHAR(60) NOT NULL,
    square_footage  INT NOT NULL,
    open_date       DATE NOT NULL
);

CREATE TABLE dim_product (
    product_id      SERIAL PRIMARY KEY,
    sku             VARCHAR(20) NOT NULL UNIQUE,
    product_name    VARCHAR(150) NOT NULL,
    category        VARCHAR(50) NOT NULL,
    subcategory     VARCHAR(50) NOT NULL,
    brand           VARCHAR(60) NOT NULL,
    unit_cost       NUMERIC(10,2) NOT NULL,
    unit_price      NUMERIC(10,2) NOT NULL,
    launch_date     DATE NOT NULL
);

CREATE TABLE dim_customer (
    customer_id     SERIAL PRIMARY KEY,
    customer_name   VARCHAR(100) NOT NULL,
    email           VARCHAR(150) NOT NULL,
    gender          VARCHAR(10),
    birth_date      DATE,
    region          VARCHAR(30) NOT NULL,
    signup_date     DATE NOT NULL,
    loyalty_tier    VARCHAR(10) NOT NULL DEFAULT 'Bronze'  -- Bronze, Silver, Gold, Platinum
);

-- ------------------------------------------------------------
-- Populate dim_date for 2021-01-01 .. 2026-12-31.
-- Range covers the historical actuals generated by the ETL pipeline
-- plus the forward horizon needed by the sales forecasting module.
-- ------------------------------------------------------------
WITH calendar AS (
    SELECT d::date AS full_date
    FROM generate_series('2021-01-01'::date, '2026-12-31'::date, interval '1 day') d
),
thanksgiving AS (
    -- 4th Thursday of November each year
    SELECT
        y AS year,
        (make_date(y, 11, 1)
            + ((4 - EXTRACT(ISODOW FROM make_date(y, 11, 1))::int + 7) % 7)
            + 21) AS thanksgiving_date
    FROM generate_series(2021, 2026) y
)
INSERT INTO dim_date (date_id, full_date, year, quarter, month, month_name, week_of_year,
                       day_of_month, day_of_week, day_name, is_weekend, is_holiday, holiday_name)
SELECT
    TO_CHAR(c.full_date, 'YYYYMMDD')::int,
    c.full_date,
    EXTRACT(YEAR FROM c.full_date)::smallint,
    EXTRACT(QUARTER FROM c.full_date)::smallint,
    EXTRACT(MONTH FROM c.full_date)::smallint,
    TRIM(TO_CHAR(c.full_date, 'Month')),
    EXTRACT(WEEK FROM c.full_date)::smallint,
    EXTRACT(DAY FROM c.full_date)::smallint,
    EXTRACT(ISODOW FROM c.full_date)::smallint,
    TRIM(TO_CHAR(c.full_date, 'Day')),
    EXTRACT(ISODOW FROM c.full_date) IN (6, 7),
    CASE
        WHEN TO_CHAR(c.full_date, 'MM-DD') IN ('01-01', '07-04', '12-24', '12-25', '12-31') THEN TRUE
        WHEN c.full_date = t.thanksgiving_date THEN TRUE
        WHEN c.full_date = t.thanksgiving_date + 1 THEN TRUE
        ELSE FALSE
    END,
    CASE
        WHEN TO_CHAR(c.full_date, 'MM-DD') = '01-01' THEN 'New Year''s Day'
        WHEN TO_CHAR(c.full_date, 'MM-DD') = '07-04' THEN 'Independence Day'
        WHEN TO_CHAR(c.full_date, 'MM-DD') = '12-24' THEN 'Christmas Eve'
        WHEN TO_CHAR(c.full_date, 'MM-DD') = '12-25' THEN 'Christmas Day'
        WHEN TO_CHAR(c.full_date, 'MM-DD') = '12-31' THEN 'New Year''s Eve'
        WHEN c.full_date = t.thanksgiving_date THEN 'Thanksgiving'
        WHEN c.full_date = t.thanksgiving_date + 1 THEN 'Black Friday'
        ELSE NULL
    END
FROM calendar c
LEFT JOIN thanksgiving t ON t.year = EXTRACT(YEAR FROM c.full_date)::int
ORDER BY c.full_date;
